//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Panel16.Shared.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Panel16.Shared.ResourceFiles.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets.
        /// </summary>
        public static string AddAssetsPage {
            get {
                return ResourceManager.GetString("AddAssetsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admins.
        /// </summary>
        public static string Admins {
            get {
                return ResourceManager.GetString("Admins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset.
        /// </summary>
        public static string AssetsPage {
            get {
                return ResourceManager.GetString("AssetsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign role.
        /// </summary>
        public static string AssignRole {
            get {
                return ResourceManager.GetString("AssignRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new hub.
        /// </summary>
        public static string Button_AddHub {
            get {
                return ResourceManager.GetString("Button_AddHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new Sensor.
        /// </summary>
        public static string Button_AddSensor {
            get {
                return ResourceManager.GetString("Button_AddSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign.
        /// </summary>
        public static string Button_Assign {
            get {
                return ResourceManager.GetString("Button_Assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load more....
        /// </summary>
        public static string Button_LoadMore {
            get {
                return ResourceManager.GetString("Button_LoadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not Invite this User.
        /// </summary>
        public static string CanNotInviteUser {
            get {
                return ResourceManager.GetString("CanNotInviteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configs Count.
        /// </summary>
        public static string ConfigsCount {
            get {
                return ResourceManager.GetString("ConfigsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string ConvertToAdmin {
            get {
                return ResourceManager.GetString("ConvertToAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessor.
        /// </summary>
        public static string ConvertToAssessor {
            get {
                return ResourceManager.GetString("ConvertToAssessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinator.
        /// </summary>
        public static string ConvertToCoordinator {
            get {
                return ResourceManager.GetString("ConvertToCoordinator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string CountryCode {
            get {
                return ResourceManager.GetString("CountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CriticalAssets.
        /// </summary>
        public static string CriticalAssetsPage {
            get {
                return ResourceManager.GetString("CriticalAssetsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeActive.
        /// </summary>
        public static string DeActive {
            get {
                return ResourceManager.GetString("DeActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string DetailsButton {
            get {
                return ResourceManager.GetString("DetailsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Mobile number to search.
        /// </summary>
        public static string EnterAUserToInvite {
            get {
                return ResourceManager.GetString("EnterAUserToInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        public static string Folders {
            get {
                return ResourceManager.GetString("Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has acces?.
        /// </summary>
        public static string HasAccess {
            get {
                return ResourceManager.GetString("HasAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hubs.
        /// </summary>
        public static string HubsPageTitle {
            get {
                return ResourceManager.GetString("HubsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password is incorrect.
        /// </summary>
        public static string InvalidCredential {
            get {
                return ResourceManager.GetString("InvalidCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite users .
        /// </summary>
        public static string Invite {
            get {
                return ResourceManager.GetString("Invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Added To Your Company.
        /// </summary>
        public static string InviteSuccessful {
            get {
                return ResourceManager.GetString("InviteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Acces.
        /// </summary>
        public static string IsPublic {
            get {
                return ResourceManager.GetString("IsPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to duplicte this item?.
        /// </summary>
        public static string ItemCopyingConfirm {
            get {
                return ResourceManager.GetString("ItemCopyingConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to Delete this item? It is not restorable!.
        /// </summary>
        public static string ItemDeletingWrning {
            get {
                return ResourceManager.GetString("ItemDeletingWrning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of simulation.
        /// </summary>
        public static string LenSimulate {
            get {
                return ResourceManager.GetString("LenSimulate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string MainPage {
            get {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Massages.
        /// </summary>
        public static string MassagesPage {
            get {
                return ResourceManager.GetString("MassagesPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Invited Users.
        /// </summary>
        public static string MyInvitedUsers {
            get {
                return ResourceManager.GetString("MyInvitedUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Configs.
        /// </summary>
        public static string NumConfigs {
            get {
                return ResourceManager.GetString("NumConfigs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizations.
        /// </summary>
        public static string Organizations {
            get {
                return ResourceManager.GetString("Organizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Url.
        /// </summary>
        public static string OrganizationUrl {
            get {
                return ResourceManager.GetString("OrganizationUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Admin Role.
        /// </summary>
        public static string RemoveAdminRole {
            get {
                return ResourceManager.GetString("RemoveAdminRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Assessor Role.
        /// </summary>
        public static string RemoveAssessorRole {
            get {
                return ResourceManager.GetString("RemoveAssessorRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Coordinator Role.
        /// </summary>
        public static string RemoveCoordinatorRole {
            get {
                return ResourceManager.GetString("RemoveCoordinatorRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Continue.
        /// </summary>
        public static string SaveAndContinue {
            get {
                return ResourceManager.GetString("SaveAndContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Hub Data.
        /// </summary>
        public static string SaveHubPage {
            get {
                return ResourceManager.GetString("SaveHubPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Organization.
        /// </summary>
        public static string SaveOrganization {
            get {
                return ResourceManager.GetString("SaveOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensors.
        /// </summary>
        public static string SensorsPage {
            get {
                return ResourceManager.GetString("SensorsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensors.
        /// </summary>
        public static string SensorsPageTitle {
            get {
                return ResourceManager.GetString("SensorsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        public static string Set {
            get {
                return ResourceManager.GetString("Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string Signup {
            get {
                return ResourceManager.GetString("Signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulation Length.
        /// </summary>
        public static string SimulationLength {
            get {
                return ResourceManager.GetString("SimulationLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Code sent to your mobile phone.
        /// </summary>
        public static string SuccessfulOtpMessage {
            get {
                return ResourceManager.GetString("SuccessfulOtpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign new Hub.
        /// </summary>
        public static string Text_AssignNewHub {
            get {
                return ResourceManager.GetString("Text_AssignNewHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign new Sensor.
        /// </summary>
        public static string Text_AssignNewSensor {
            get {
                return ResourceManager.GetString("Text_AssignNewSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copied..
        /// </summary>
        public static string Text_CopyToast {
            get {
                return ResourceManager.GetString("Text_CopyToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU Temperature.
        /// </summary>
        public static string Text_CpuTemperature {
            get {
                return ResourceManager.GetString("Text_CpuTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Text_Day {
            get {
                return ResourceManager.GetString("Text_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this item?.
        /// </summary>
        public static string Text_DeleteConfirm {
            get {
                return ResourceManager.GetString("Text_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Hub.
        /// </summary>
        public static string Text_EditHub {
            get {
                return ResourceManager.GetString("Text_EditHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Sensor.
        /// </summary>
        public static string Text_EditSensor {
            get {
                return ResourceManager.GetString("Text_EditSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electricity Current(Amper).
        /// </summary>
        public static string Text_ElectricityCurrent {
            get {
                return ResourceManager.GetString("Text_ElectricityCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hub.
        /// </summary>
        public static string Text_Hub {
            get {
                return ResourceManager.GetString("Text_Hub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hub data saved..
        /// </summary>
        public static string Text_HubSuccessfulSaveMessage {
            get {
                return ResourceManager.GetString("Text_HubSuccessfulSaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not be assigned to you..
        /// </summary>
        public static string Text_IsNotAssignable {
            get {
                return ResourceManager.GetString("Text_IsNotAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last seen time.
        /// </summary>
        public static string Text_LastSeen {
            get {
                return ResourceManager.GetString("Text_LastSeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Level.
        /// </summary>
        public static string Text_LightLevel {
            get {
                return ResourceManager.GetString("Text_LightLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light(LUX).
        /// </summary>
        public static string Text_lux {
            get {
                return ResourceManager.GetString("Text_lux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waringng on greater electricity current.
        /// </summary>
        public static string Text_MaxElectricityWarning {
            get {
                return ResourceManager.GetString("Text_MaxElectricityWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waringng on less electricity temperature.
        /// </summary>
        public static string Text_MaxTempratureWarning {
            get {
                return ResourceManager.GetString("Text_MaxTempratureWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waringng on less electricity current.
        /// </summary>
        public static string Text_MinElectricityWarning {
            get {
                return ResourceManager.GetString("Text_MinElectricityWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waringng on greater electricity temperature.
        /// </summary>
        public static string Text_MinTemperatureWarning {
            get {
                return ResourceManager.GetString("Text_MinTemperatureWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Hubs.
        /// </summary>
        public static string Text_MyHubs {
            get {
                return ResourceManager.GetString("Text_MyHubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Sensors.
        /// </summary>
        public static string Text_MySensors {
            get {
                return ResourceManager.GetString("Text_MySensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data.
        /// </summary>
        public static string Text_NeverSent {
            get {
                return ResourceManager.GetString("Text_NeverSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night.
        /// </summary>
        public static string Text_Night {
            get {
                return ResourceManager.GetString("Text_Night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Text_Password {
            get {
                return ResourceManager.GetString("Text_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Key.
        /// </summary>
        public static string Text_PublicKeyTitle {
            get {
                return ResourceManager.GetString("Text_PublicKeyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q1 Average.
        /// </summary>
        public static string Text_Q1Average {
            get {
                return ResourceManager.GetString("Text_Q1Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q2 Average.
        /// </summary>
        public static string Text_Q2Average {
            get {
                return ResourceManager.GetString("Text_Q2Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q3 Average.
        /// </summary>
        public static string Text_Q3Average {
            get {
                return ResourceManager.GetString("Text_Q3Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q4 Average.
        /// </summary>
        public static string Text_Q4Average {
            get {
                return ResourceManager.GetString("Text_Q4Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Data.
        /// </summary>
        public static string Text_SavePage {
            get {
                return ResourceManager.GetString("Text_SavePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret Key.
        /// </summary>
        public static string Text_SecretKeyLabel {
            get {
                return ResourceManager.GetString("Text_SecretKeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor.
        /// </summary>
        public static string Text_Sensor {
            get {
                return ResourceManager.GetString("Text_Sensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Sent data.
        /// </summary>
        public static string Text_SentData {
            get {
                return ResourceManager.GetString("Text_SentData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string Text_SignOut {
            get {
                return ResourceManager.GetString("Text_SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item deleted successfully..
        /// </summary>
        public static string Text_SuccessfulDeleteMessage {
            get {
                return ResourceManager.GetString("Text_SuccessfulDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Item data saved.
        /// </summary>
        public static string Text_SuccessfulSaveMessage {
            get {
                return ResourceManager.GetString("Text_SuccessfulSaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string Text_Temperature {
            get {
                return ResourceManager.GetString("Text_Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Text_Today {
            get {
                return ResourceManager.GetString("Text_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Average.
        /// </summary>
        public static string Text_TotalAverage {
            get {
                return ResourceManager.GetString("Text_TotalAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occured.
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        public static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string Verify {
            get {
                return ResourceManager.GetString("Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string VerifyTitle {
            get {
                return ResourceManager.GetString("VerifyTitle", resourceCulture);
            }
        }
    }
}
