name: Deploy to Afranet

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy new files
        uses: garygrossgarten/github-action-scp@v0.8.0
        with:
          local: '.'
          remote: '/SimulationHost'
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          exclude: '.git'

      - name: Run script
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.HOST }} "cd /SimulationHost/HostServer && dotnet run"